### PR TITLE
ES native promises & `inspect` method

### PR DESCRIPTION
**Pull request by developius**
Hi Austin,

This is a PR containing the following changes:
- removes bluebird dependency & replaces with drop in replacement (native ES promises)
- refactor FaaS module into a class
- add new method  for finding out info about a specific function
- update & add tests to reflect changes

The reason behind it is because I wanted to add an extra method `inspect` originally, but basically that snowballed into modifying the lib to not use bluebird and instead migrate to native ES promises. You can check out the tests, I've added one but mostly they've stayed the same - so no breaking changes except that the `FaaS` module is now a class, and therefore has to be used like `new FaaS(gateway)`.

Forgive me, I don't know `tape` or `nocks` very well so I may have implemented the tests in a suboptimal way - just shout if so 🙈 

I know this is a pretty big change, so just shout if you'd rather not merge & I'll maintain the fork instead 😃 

Signed-off-by: Finnian Anderson <get@finnian.io>

### CODE REVIEW

**Comment by austinfrey** [comment]
@developius thanks for the PR!! I'll look at it today. So far I like the changes. Would you might submitting it to the `openfaas-incubator/node-openfaas` repo instead though? i think this one will be going away. Thanks again!

**Comment by developius** [comment]
Whoops! Sure thing, will re-open there 👍

**Comment by developius** [comment]
Closing in favour of openfaas-incubator/node-openfaas#1

**Comment by developius** [comment]
Closing in favour of openfaas-incubator/node-openfaas#1

**Pull request closed without merging**
